language: python
sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"
  - "pypy3"

matrix:
  include:
  - python: 2.6
    dist: trusty
  - python: 3.2
    dist: trusty
  - python: 3.3
    dist: trusty

install:
  - pip install tox-travis

script:
  - tox

notifications:
  email: false
